#!/usr/bin/env bash
#
# baba database helper — native Windows (Git Bash) edition.
#
# Runs a *project-local* PostgreSQL cluster from a portable PostgreSQL install,
# with NO Windows service and NO admin rights:
#   - binaries : $PGHOME           (default: ~/pgsql — the extracted 18.x zip)
#   - data dir : backend/.pgdata   (gitignored)
#   - port     : 5432 on 127.0.0.1 only, trust auth (local dev)
#   - app role : baba / baba       app db: baba
#   - plus an `admin` / admin SUPERUSER role for convenience (psql, GUI tools)
#
# Usage:
#   ./scripts/db-windows.sh init     # initdb (first run) + start + create role/db (idempotent)
#   ./scripts/db-windows.sh start    # start the cluster
#   ./scripts/db-windows.sh stop     # stop the cluster
#   ./scripts/db-windows.sh status   # cluster status
#   ./scripts/db-windows.sh psql     # psql into the baba database
#   ./scripts/db-windows.sh reset    # DROP + recreate the baba database (destructive)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PGHOME="${PGHOME:-$HOME/pgsql}"
PG_BIN="$PGHOME/bin"
PGDATA="${PGDATA:-$BACKEND_DIR/.pgdata}"
LOGFILE="$PGDATA/server.log"
ENV_FILE="$BACKEND_DIR/.env"

PGPORT="${PGPORT:-5432}"
SUPERUSER="postgres"
APP_USER="baba"; APP_DB="baba"; APP_PW="baba"

if [[ ! -x "$PG_BIN/psql.exe" ]]; then
  echo "ERROR: PostgreSQL binaries not found at $PG_BIN" >&2
  echo "       Set PGHOME to your portable PostgreSQL directory (the one containing bin/)." >&2
  exit 1
fi

super_psql() { "$PG_BIN/psql.exe" -h 127.0.0.1 -p "$PGPORT" -U "$SUPERUSER" -d postgres -v ON_ERROR_STOP=1 "$@"; }
is_running() { "$PG_BIN/pg_ctl.exe" -D "$PGDATA" status >/dev/null 2>&1; }

init_cluster() {
  if [[ ! -f "$PGDATA/PG_VERSION" ]]; then
    echo "initdb -> $PGDATA"
    "$PG_BIN/initdb.exe" -D "$PGDATA" -U "$SUPERUSER" -A trust -E UTF8 >/dev/null
  fi
}

start_cluster() {
  init_cluster
  if is_running; then return 0; fi
  echo "Starting cluster on 127.0.0.1:$PGPORT ($PGDATA) ..."
  "$PG_BIN/pg_ctl.exe" -D "$PGDATA" -l "$LOGFILE" -w \
    -o "-p $PGPORT -c listen_addresses=127.0.0.1" start
}

stop_cluster() {
  if is_running; then "$PG_BIN/pg_ctl.exe" -D "$PGDATA" -m fast stop; else echo "Not running."; fi
}

ensure_role_db() {
  # CREATE ... attempts are tolerant (role/db may already exist); the ALTERs make
  # the state authoritative (password / ownership) every run. Values are fixed
  # literals, so no injection surface.
  super_psql -c "CREATE ROLE $APP_USER LOGIN PASSWORD '$APP_PW';"        2>/dev/null || true
  super_psql -c "ALTER  ROLE $APP_USER WITH LOGIN PASSWORD '$APP_PW';"
  super_psql -c "CREATE ROLE admin LOGIN SUPERUSER PASSWORD 'admin';"    2>/dev/null || true
  super_psql -c "ALTER  ROLE admin WITH LOGIN SUPERUSER PASSWORD 'admin';"
  super_psql -c "CREATE DATABASE $APP_DB OWNER $APP_USER;"               2>/dev/null || true
  super_psql -c "ALTER  DATABASE $APP_DB OWNER TO $APP_USER;"
}

write_env_if_missing() {
  [[ -f "$ENV_FILE" ]] && return 0
  echo "Writing $ENV_FILE with a fresh JWT secret ..."
  local jwt
  jwt="$(openssl rand -hex 32 2>/dev/null || { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; })"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/db-windows.sh — do NOT commit. See .env.example.
PGHOST=127.0.0.1
PGPORT=$PGPORT
PGDATABASE=$APP_DB
PGUSER=$APP_USER
PGPASSWORD=$APP_PW
DATABASE_URL=postgres://$APP_USER:$APP_PW@127.0.0.1:$PGPORT/$APP_DB

JWT_SECRET=$jwt
JWT_TTL_SECONDS=604800

BIND_ADDR=127.0.0.1:8080
COOKIE_NAME=auth_token
COOKIE_SECURE=false
CORS_ORIGIN=http://127.0.0.1:5174

RUST_LOG=info,tower_http=info,baba_backend=debug
EOF
}

case "${1:-}" in
  init)
    start_cluster
    ensure_role_db
    write_env_if_missing
    echo
    echo "OK  postgres://$APP_USER:***@127.0.0.1:$PGPORT/$APP_DB"
    echo "    data dir: $PGDATA"
    echo "    manage:   ./scripts/db-windows.sh {start|stop|status|psql|reset}"
    ;;
  start)  start_cluster ;;
  stop)   stop_cluster ;;
  status) "$PG_BIN/pg_ctl.exe" -D "$PGDATA" status || true ;;
  psql)   shift; PGPASSWORD="$APP_PW" "$PG_BIN/psql.exe" -h 127.0.0.1 -p "$PGPORT" -U "$APP_USER" -d "$APP_DB" "$@" ;;
  reset)
    start_cluster
    super_psql -c "DROP DATABASE IF EXISTS $APP_DB;"
    super_psql -c "CREATE DATABASE $APP_DB OWNER $APP_USER;"
    echo "Recreated empty database '$APP_DB'."
    ;;
  *) echo "Usage: $0 {init|start|stop|status|psql|reset}" >&2; exit 1 ;;
esac
