#!/usr/bin/env bash
#
# Manage baba's database INSIDE the shared rust-demo PostgreSQL cluster.
#
# baba does NOT run its own cluster. It reuses one shared cluster (data dir at
# ~/.local/pgdata, port 5432) that holds every project's database, but baba is
# otherwise fully isolated: its own least-privilege role `baba`, its own
# password, and its own database `baba`. Only the physical server is shared —
# credentials are NOT.
#
# The shared cluster is bootstrapped by rust-demo's scripts/db.sh (it owns the
# initdb). Cross-project coupling note: starting/stopping the cluster from here
# affects every project using it, since it's the same physical cluster.
#
# Usage:
#   ./scripts/db.sh init      # ensure shared cluster up + create role/db + write .env (idempotent)
#   ./scripts/db.sh start     # start the shared cluster (rust-demo's data dir)
#   ./scripts/db.sh stop      # stop the shared cluster  (⚠ also stops rust-demo)
#   ./scripts/db.sh status    # show shared cluster status
#   ./scripts/db.sh psql      # open psql connected to baba's database
#   ./scripts/db.sh reset     # DROP baba's database and recreate it (destructive, baba only)
#
set -euo pipefail

# --- Resolve locations -------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$BACKEND_DIR/.env"

# The shared cluster lives in rust-demo's backend. Override via env if your
# checkout is laid out differently.
WORKSPACE_DIR="$(cd "$BACKEND_DIR/../.." && pwd)"
SHARED_PGDATA="${SHARED_PGDATA:-$HOME/.local/pgdata}"
LOGFILE="$SHARED_PGDATA/server.log"

# Pick the newest installed PostgreSQL bin dir (psql/pg_ctl aren't on PATH).
PG_BIN="$(ls -d /usr/lib/postgresql/*/bin 2>/dev/null | sort -V | tail -1 || true)"
if [[ -z "${PG_BIN:-}" || ! -x "$PG_BIN/psql" ]]; then
  echo "ERROR: could not find PostgreSQL binaries under /usr/lib/postgresql/*/bin" >&2
  exit 1
fi

# --- Connection settings -----------------------------------------------------
PGPORT="${PGPORT:-5432}"      # shared cluster port (default Postgres port)
SUPERUSER="postgres"          # local trust superuser on the shared cluster
APP_USER="baba"               # baba's OWN least-privilege role
APP_DB="baba"                 # baba's OWN isolated database within the shared cluster

# psql talking to the shared cluster as the local trusted superuser over its socket.
super_psql() { "$PG_BIN/psql" -h "$SHARED_PGDATA" -p "$PGPORT" -U "$SUPERUSER" -d postgres -v ON_ERROR_STOP=1 "$@"; }

is_running() { "$PG_BIN/pg_ctl" -D "$SHARED_PGDATA" status >/dev/null 2>&1; }

require_shared_cluster() {
  if [[ ! -f "$SHARED_PGDATA/PG_VERSION" ]]; then
    echo "ERROR: shared cluster not found at $SHARED_PGDATA" >&2
    echo "       Initialize it first:  (cd $WORKSPACE_DIR/rust-demo/backend && ./scripts/db.sh init)" >&2
    exit 1
  fi
}

start_cluster() {
  require_shared_cluster
  if is_running; then return 0; fi
  echo "Starting shared cluster on 127.0.0.1:$PGPORT ($SHARED_PGDATA) ..."
  "$PG_BIN/pg_ctl" -D "$SHARED_PGDATA" -l "$LOGFILE" -w \
    -o "-p $PGPORT -k $SHARED_PGDATA -c listen_addresses=127.0.0.1" start
}

stop_cluster() {
  if is_running; then
    echo "Stopping shared cluster (⚠ this also stops rust-demo) ..."
    "$PG_BIN/pg_ctl" -D "$SHARED_PGDATA" -m fast stop
  else
    echo "Cluster not running."
  fi
}

write_env_if_missing() {
  if [[ -f "$ENV_FILE" ]]; then return 0; fi
  echo "Writing $ENV_FILE with freshly generated secrets ..."
  local db_pw jwt_secret
  db_pw="$(openssl rand -hex 16)"
  jwt_secret="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/db.sh — do NOT commit. See .env.example for the template.
# baba shares one PostgreSQL cluster on :$PGPORT (same server, all projects) but
# is otherwise isolated: its own role '$APP_USER', own password, own database '$APP_DB'.

# --- Database (shared cluster at ~/.local/pgdata; bootstrapped by rust-demo) ---
PGHOST=127.0.0.1
PGPORT=$PGPORT
PGDATABASE=$APP_DB
PGUSER=$APP_USER
PGPASSWORD=$db_pw
DATABASE_URL=postgres://$APP_USER:$db_pw@127.0.0.1:$PGPORT/$APP_DB

# --- Auth (baba-specific secret) ---
JWT_SECRET=$jwt_secret
JWT_TTL_SECONDS=604800        # 7 days

# --- HTTP server ---
BIND_ADDR=127.0.0.1:8080
COOKIE_NAME=auth_token
COOKIE_SECURE=false           # set true when served over HTTPS
CORS_ORIGIN=http://127.0.0.1:5174

RUST_LOG=info,tower_http=info,baba_backend=debug
EOF
  chmod 600 "$ENV_FILE"
}

load_app_creds() {
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
}

ensure_role_and_db() {
  load_app_creds
  # Create baba's own role if missing, and (re)set its password to match .env.
  super_psql -c "DO \$\$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APP_USER') THEN
        CREATE ROLE $APP_USER LOGIN PASSWORD '$PGPASSWORD';
      ELSE
        ALTER ROLE $APP_USER WITH LOGIN PASSWORD '$PGPASSWORD';
      END IF;
    END \$\$;"
  # Create the database if missing, otherwise make sure baba owns it (it may
  # have been created earlier under a different owner).
  if ! super_psql -tAc "SELECT 1 FROM pg_database WHERE datname='$APP_DB'" | grep -q 1; then
    super_psql -c "CREATE DATABASE $APP_DB OWNER $APP_USER;"
  else
    super_psql -c "ALTER DATABASE $APP_DB OWNER TO $APP_USER;"
  fi
}

cmd_init() {
  start_cluster
  write_env_if_missing
  ensure_role_and_db
  echo
  echo "✅ Database ready:  postgres://$APP_USER:***@127.0.0.1:$PGPORT/$APP_DB"
  echo "   Shared cluster:  $SHARED_PGDATA"
  echo "   Manage with: ./scripts/db.sh {start|stop|status|psql}"
}

cmd_reset() {
  start_cluster
  load_app_creds
  super_psql -c "DROP DATABASE IF EXISTS $APP_DB;"
  super_psql -c "CREATE DATABASE $APP_DB OWNER $APP_USER;"
  echo "Recreated empty database '$APP_DB'."
}

cmd_psql() {
  start_cluster
  load_app_creds
  # Forward any extra args (e.g. -c "select ...") straight to psql.
  PGPASSWORD="$PGPASSWORD" "$PG_BIN/psql" -h 127.0.0.1 -p "$PGPORT" -U "$APP_USER" -d "$APP_DB" "$@"
}

case "${1:-}" in
  init)   cmd_init ;;
  start)  start_cluster ;;
  stop)   stop_cluster ;;
  status) "$PG_BIN/pg_ctl" -D "$SHARED_PGDATA" status || true ;;
  psql)   shift; cmd_psql "$@" ;;
  reset)  cmd_reset ;;
  *) echo "Usage: $0 {init|start|stop|status|psql|reset}" >&2; exit 1 ;;
esac
