#!/usr/bin/env bash
#
# Manage a self-contained, project-local PostgreSQL cluster.
#
# Why this exists: the machine already runs a system Postgres on :5432 that is
# password-locked and not ours to administer. Instead of guessing secrets, we
# stand up our own cluster (own data dir, own port, no sudo) that the project
# fully owns. Credentials are generated once and written to backend/.env.
#
# Usage:
#   ./scripts/db.sh init     # create cluster + role + database + .env (idempotent)
#   ./scripts/db.sh start     # start the cluster
#   ./scripts/db.sh stop      # stop the cluster
#   ./scripts/db.sh status    # show cluster status
#   ./scripts/db.sh psql      # open psql connected to the app database
#   ./scripts/db.sh reset     # DROP the database and recreate it (destructive)
#
set -euo pipefail

# --- Resolve locations -------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PGDATA="$BACKEND_DIR/.pgdata"
ENV_FILE="$BACKEND_DIR/.env"
LOGFILE="$PGDATA/server.log"

# Pick the newest installed PostgreSQL bin dir (initdb/pg_ctl aren't on PATH).
PG_BIN="$(ls -d /usr/lib/postgresql/*/bin 2>/dev/null | sort -V | tail -1 || true)"
if [[ -z "${PG_BIN:-}" || ! -x "$PG_BIN/initdb" ]]; then
  echo "ERROR: could not find PostgreSQL binaries under /usr/lib/postgresql/*/bin" >&2
  exit 1
fi

# --- Cluster connection settings (the cluster itself) ------------------------
PGPORT="${PGPORT:-5433}"
SUPERUSER="postgres"          # bootstrap superuser (local trust auth)
APP_USER="authapp"            # least-privilege application role
APP_DB="auth_demo"

# psql talking to the cluster as the local trusted superuser over the unix socket.
super_psql() { "$PG_BIN/psql" -h "$PGDATA" -p "$PGPORT" -U "$SUPERUSER" -d postgres -v ON_ERROR_STOP=1 "$@"; }

is_running() { "$PG_BIN/pg_ctl" -D "$PGDATA" status >/dev/null 2>&1; }

start_cluster() {
  if is_running; then return 0; fi
  echo "Starting cluster on 127.0.0.1:$PGPORT ..."
  # -k sets the unix socket dir to the data dir; listen only on loopback.
  "$PG_BIN/pg_ctl" -D "$PGDATA" -l "$LOGFILE" -w \
    -o "-p $PGPORT -k $PGDATA -c listen_addresses=127.0.0.1" start
}

stop_cluster() {
  if is_running; then
    "$PG_BIN/pg_ctl" -D "$PGDATA" -m fast stop
  else
    echo "Cluster not running."
  fi
}

write_env_if_missing() {
  if [[ -f "$ENV_FILE" ]]; then return 0; fi
  echo "Writing $ENV_FILE with freshly generated secrets ..."
  local db_pw jwt_secret
  db_pw="$(openssl rand -hex 16)"
  jwt_secret="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/db.sh — do NOT commit. See .env.example for the template.

# --- Database (project-local cluster managed by scripts/db.sh) ---
PGHOST=127.0.0.1
PGPORT=$PGPORT
PGDATABASE=$APP_DB
PGUSER=$APP_USER
PGPASSWORD=$db_pw
DATABASE_URL=postgres://$APP_USER:$db_pw@127.0.0.1:$PGPORT/$APP_DB

# --- Auth ---
JWT_SECRET=$jwt_secret
JWT_TTL_SECONDS=604800        # 7 days

# --- HTTP server ---
BIND_ADDR=127.0.0.1:8080
COOKIE_NAME=auth_token
COOKIE_SECURE=false           # set true when served over HTTPS
CORS_ORIGIN=http://127.0.0.1:5174

RUST_LOG=info,tower_http=info,auth_backend=debug
EOF
  chmod 600 "$ENV_FILE"
}

load_app_creds() {
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
}

ensure_role_and_db() {
  load_app_creds
  # Create the app role if missing, and (re)set its password to match .env.
  super_psql -c "DO \$\$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APP_USER') THEN
        CREATE ROLE $APP_USER LOGIN PASSWORD '$PGPASSWORD';
      ELSE
        ALTER ROLE $APP_USER WITH LOGIN PASSWORD '$PGPASSWORD';
      END IF;
    END \$\$;"
  # Create the database if missing (owned by the app role).
  if ! super_psql -tAc "SELECT 1 FROM pg_database WHERE datname='$APP_DB'" | grep -q 1; then
    super_psql -c "CREATE DATABASE $APP_DB OWNER $APP_USER;"
  fi
}

cmd_init() {
  if [[ ! -f "$PGDATA/PG_VERSION" ]]; then
    echo "Initializing new cluster in $PGDATA ..."
    mkdir -p "$PGDATA"
    chmod 700 "$PGDATA"
    # local connections: trust (so we can administer without a password)
    # host  connections: scram-sha-256 (the app authenticates with a password)
    "$PG_BIN/initdb" -D "$PGDATA" -U "$SUPERUSER" -E UTF8 \
      --auth-local=trust --auth-host=scram-sha-256 >/dev/null
  fi
  start_cluster
  write_env_if_missing
  ensure_role_and_db
  echo
  echo "✅ Database ready:  postgres://$APP_USER:***@127.0.0.1:$PGPORT/$APP_DB"
  echo "   Manage with: ./scripts/db.sh {start|stop|status|psql}"
}

cmd_reset() {
  start_cluster
  load_app_creds
  super_psql -c "DROP DATABASE IF EXISTS $APP_DB;"
  super_psql -c "CREATE DATABASE $APP_DB OWNER $APP_USER;"
  echo "Recreated empty database '$APP_DB'."
}

cmd_psql() {
  start_cluster
  load_app_creds
  # Forward any extra args (e.g. -c "select ...") straight to psql.
  PGPASSWORD="$PGPASSWORD" "$PG_BIN/psql" -h 127.0.0.1 -p "$PGPORT" -U "$APP_USER" -d "$APP_DB" "$@"
}

case "${1:-}" in
  init)   cmd_init ;;
  start)  start_cluster ;;
  stop)   stop_cluster ;;
  status) "$PG_BIN/pg_ctl" -D "$PGDATA" status || true ;;
  psql)   shift; cmd_psql "$@" ;;
  reset)  cmd_reset ;;
  *) echo "Usage: $0 {init|start|stop|status|psql|reset}" >&2; exit 1 ;;
esac
